namespace Voltaic.Core
{
    using System.Collections.Generic;
    using System.Text.Json;
    using System.Text.Json.Nodes;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Source-generated metadata for every type Voltaic serializes, and for the JSON DOM, primitive, and collection
    /// types applications commonly pass as <see cref="object"/>. Metadata only: the runtime options (naming,
    /// null handling, converters) apply exactly as they do with reflection. Thread-safe.
    /// </summary>
    [JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Metadata)]
    [JsonSerializable(typeof(object))]
    [JsonSerializable(typeof(JsonEmptyObject))]
    [JsonSerializable(typeof(Voltaic.Mcp.McpHttpClient.ResultTypeProbe), TypeInfoPropertyName = "McpResultTypeProbe")]
    [JsonSerializable(typeof(List<JsonRpcRequest>))]
    [JsonSerializable(typeof(List<JsonRpcResponse>))]
    [JsonSerializable(typeof(JsonRpcRequest[]))]
    [JsonSerializable(typeof(JsonRpcResponse[]))]
    [JsonSerializable(typeof(string))]
    [JsonSerializable(typeof(bool))]
    [JsonSerializable(typeof(int))]
    [JsonSerializable(typeof(long))]
    [JsonSerializable(typeof(short))]
    [JsonSerializable(typeof(byte))]
    [JsonSerializable(typeof(sbyte))]
    [JsonSerializable(typeof(uint))]
    [JsonSerializable(typeof(ulong))]
    [JsonSerializable(typeof(ushort))]
    [JsonSerializable(typeof(float))]
    [JsonSerializable(typeof(double))]
    [JsonSerializable(typeof(decimal))]
    [JsonSerializable(typeof(char))]
    [JsonSerializable(typeof(bool?))]
    [JsonSerializable(typeof(int?))]
    [JsonSerializable(typeof(long?))]
    [JsonSerializable(typeof(double?))]
    [JsonSerializable(typeof(decimal?))]
    [JsonSerializable(typeof(float?))]
    [JsonSerializable(typeof(System.DateTime))]
    [JsonSerializable(typeof(System.DateTimeOffset))]
    [JsonSerializable(typeof(System.Guid))]
    [JsonSerializable(typeof(System.TimeSpan))]
    [JsonSerializable(typeof(System.Uri))]
    [JsonSerializable(typeof(JsonElement))]
    [JsonSerializable(typeof(JsonElement?))]
    [JsonSerializable(typeof(JsonDocument))]
    [JsonSerializable(typeof(JsonNode))]
    [JsonSerializable(typeof(JsonObject))]
    [JsonSerializable(typeof(JsonArray))]
    [JsonSerializable(typeof(JsonValue))]
    [JsonSerializable(typeof(string[]))]
    [JsonSerializable(typeof(object[]))]
    [JsonSerializable(typeof(int[]))]
    [JsonSerializable(typeof(long[]))]
    [JsonSerializable(typeof(double[]))]
    [JsonSerializable(typeof(bool[]))]
    [JsonSerializable(typeof(JsonElement[]))]
    [JsonSerializable(typeof(List<object>))]
    [JsonSerializable(typeof(List<string>))]
    [JsonSerializable(typeof(List<int>))]
    [JsonSerializable(typeof(List<long>))]
    [JsonSerializable(typeof(List<double>))]
    [JsonSerializable(typeof(List<JsonElement>))]
    [JsonSerializable(typeof(List<JsonNode>))]
    [JsonSerializable(typeof(Dictionary<string, object>))]
    [JsonSerializable(typeof(Dictionary<string, string>))]
    [JsonSerializable(typeof(Dictionary<string, JsonElement>))]
    [JsonSerializable(typeof(Dictionary<string, JsonNode>))]
    [JsonSerializable(typeof(Dictionary<string, int>))]
    [JsonSerializable(typeof(Dictionary<string, long>))]
    [JsonSerializable(typeof(Dictionary<string, double>))]
    [JsonSerializable(typeof(Dictionary<string, bool>))]
    [JsonSerializable(typeof(IDictionary<string, object>))]
    [JsonSerializable(typeof(IReadOnlyDictionary<string, object>))]
    [JsonSerializable(typeof(IEnumerable<object>))]
    [JsonSerializable(typeof(IList<object>))]
    [JsonSerializable(typeof(IReadOnlyList<object>))]
    [JsonSerializable(typeof(Voltaic.A2A.AgentCapabilities), TypeInfoPropertyName = "A2AAgentCapabilities")]
    [JsonSerializable(typeof(Voltaic.A2A.AgentCard), TypeInfoPropertyName = "A2AAgentCard")]
    [JsonSerializable(typeof(Voltaic.A2A.AgentCardSignature), TypeInfoPropertyName = "A2AAgentCardSignature")]
    [JsonSerializable(typeof(Voltaic.A2A.AgentExtension), TypeInfoPropertyName = "A2AAgentExtension")]
    [JsonSerializable(typeof(Voltaic.A2A.AgentInterface), TypeInfoPropertyName = "A2AAgentInterface")]
    [JsonSerializable(typeof(Voltaic.A2A.AgentProvider), TypeInfoPropertyName = "A2AAgentProvider")]
    [JsonSerializable(typeof(Voltaic.A2A.AgentSkill), TypeInfoPropertyName = "A2AAgentSkill")]
    [JsonSerializable(typeof(Voltaic.A2A.AgentTask), TypeInfoPropertyName = "A2AAgentTask")]
    [JsonSerializable(typeof(Voltaic.A2A.ApiKeySecurityScheme), TypeInfoPropertyName = "A2AApiKeySecurityScheme")]
    [JsonSerializable(typeof(Voltaic.A2A.Artifact), TypeInfoPropertyName = "A2AArtifact")]
    [JsonSerializable(typeof(Voltaic.A2A.AuthenticationInfo), TypeInfoPropertyName = "A2AAuthenticationInfo")]
    [JsonSerializable(typeof(Voltaic.A2A.CancelTaskRequest), TypeInfoPropertyName = "A2ACancelTaskRequest")]
    [JsonSerializable(typeof(Voltaic.A2A.CreateTaskPushNotificationConfigRequest), TypeInfoPropertyName = "A2ACreateTaskPushNotificationConfigRequest")]
    [JsonSerializable(typeof(Voltaic.A2A.DeleteTaskPushNotificationConfigRequest), TypeInfoPropertyName = "A2ADeleteTaskPushNotificationConfigRequest")]
    [JsonSerializable(typeof(Voltaic.A2A.GetExtendedAgentCardRequest), TypeInfoPropertyName = "A2AGetExtendedAgentCardRequest")]
    [JsonSerializable(typeof(Voltaic.A2A.GetTaskPushNotificationConfigRequest), TypeInfoPropertyName = "A2AGetTaskPushNotificationConfigRequest")]
    [JsonSerializable(typeof(Voltaic.A2A.GetTaskRequest), TypeInfoPropertyName = "A2AGetTaskRequest")]
    [JsonSerializable(typeof(Voltaic.A2A.HttpAuthSecurityScheme), TypeInfoPropertyName = "A2AHttpAuthSecurityScheme")]
    [JsonSerializable(typeof(Voltaic.A2A.ListTaskPushNotificationConfigRequest), TypeInfoPropertyName = "A2AListTaskPushNotificationConfigRequest")]
    [JsonSerializable(typeof(Voltaic.A2A.ListTaskPushNotificationConfigResponse), TypeInfoPropertyName = "A2AListTaskPushNotificationConfigResponse")]
    [JsonSerializable(typeof(Voltaic.A2A.ListTasksRequest), TypeInfoPropertyName = "A2AListTasksRequest")]
    [JsonSerializable(typeof(Voltaic.A2A.ListTasksResponse), TypeInfoPropertyName = "A2AListTasksResponse")]
    [JsonSerializable(typeof(Voltaic.A2A.Message), TypeInfoPropertyName = "A2AMessage")]
    [JsonSerializable(typeof(Voltaic.A2A.MutualTlsSecurityScheme), TypeInfoPropertyName = "A2AMutualTlsSecurityScheme")]
    [JsonSerializable(typeof(Voltaic.A2A.OAuth2SecurityScheme), TypeInfoPropertyName = "A2AOAuth2SecurityScheme")]
    [JsonSerializable(typeof(Voltaic.A2A.OAuthFlow), TypeInfoPropertyName = "A2AOAuthFlow")]
    [JsonSerializable(typeof(Voltaic.A2A.OAuthFlows), TypeInfoPropertyName = "A2AOAuthFlows")]
    [JsonSerializable(typeof(Voltaic.A2A.OpenIdConnectSecurityScheme), TypeInfoPropertyName = "A2AOpenIdConnectSecurityScheme")]
    [JsonSerializable(typeof(Voltaic.A2A.Part), TypeInfoPropertyName = "A2APart")]
    [JsonSerializable(typeof(Voltaic.A2A.PushNotificationConfig), TypeInfoPropertyName = "A2APushNotificationConfig")]
    [JsonSerializable(typeof(Voltaic.A2A.SecurityRequirement), TypeInfoPropertyName = "A2ASecurityRequirement")]
    [JsonSerializable(typeof(Voltaic.A2A.SecurityScheme), TypeInfoPropertyName = "A2ASecurityScheme")]
    [JsonSerializable(typeof(Voltaic.A2A.SendMessageConfiguration), TypeInfoPropertyName = "A2ASendMessageConfiguration")]
    [JsonSerializable(typeof(Voltaic.A2A.SendMessageRequest), TypeInfoPropertyName = "A2ASendMessageRequest")]
    [JsonSerializable(typeof(Voltaic.A2A.SendMessageResponse), TypeInfoPropertyName = "A2ASendMessageResponse")]
    [JsonSerializable(typeof(Voltaic.A2A.StreamResponse), TypeInfoPropertyName = "A2AStreamResponse")]
    [JsonSerializable(typeof(Voltaic.A2A.SubscribeToTaskRequest), TypeInfoPropertyName = "A2ASubscribeToTaskRequest")]
    [JsonSerializable(typeof(Voltaic.A2A.TaskArtifactUpdateEvent), TypeInfoPropertyName = "A2ATaskArtifactUpdateEvent")]
    [JsonSerializable(typeof(Voltaic.A2A.TaskPushNotificationConfig), TypeInfoPropertyName = "A2ATaskPushNotificationConfig")]
    [JsonSerializable(typeof(Voltaic.A2A.TaskStatus), TypeInfoPropertyName = "A2ATaskStatus")]
    [JsonSerializable(typeof(Voltaic.A2A.TaskStatusUpdateEvent), TypeInfoPropertyName = "A2ATaskStatusUpdateEvent")]
    [JsonSerializable(typeof(Voltaic.Core.JsonRpcError), TypeInfoPropertyName = "CoreJsonRpcError")]
    [JsonSerializable(typeof(Voltaic.Core.JsonRpcRequest), TypeInfoPropertyName = "CoreJsonRpcRequest")]
    [JsonSerializable(typeof(Voltaic.Core.JsonRpcResponse), TypeInfoPropertyName = "CoreJsonRpcResponse")]
    [JsonSerializable(typeof(Voltaic.Core.RpcAddArguments), TypeInfoPropertyName = "CoreRpcAddArguments")]
    [JsonSerializable(typeof(Voltaic.Core.RpcEchoArguments), TypeInfoPropertyName = "CoreRpcEchoArguments")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpAnnotations), TypeInfoPropertyName = "McpMcpAnnotations")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpAudioContent), TypeInfoPropertyName = "McpMcpAudioContent")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpBlobResourceContents), TypeInfoPropertyName = "McpMcpBlobResourceContents")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpCancelledNotification), TypeInfoPropertyName = "McpMcpCancelledNotification")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpClientCapabilities), TypeInfoPropertyName = "McpMcpClientCapabilities")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpCompleteRequest), TypeInfoPropertyName = "McpMcpCompleteRequest")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpCompleteResult), TypeInfoPropertyName = "McpMcpCompleteResult")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpCompletion), TypeInfoPropertyName = "McpMcpCompletion")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpCompletionArgument), TypeInfoPropertyName = "McpMcpCompletionArgument")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpCompletionContext), TypeInfoPropertyName = "McpMcpCompletionContext")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpCompletionReference), TypeInfoPropertyName = "McpMcpCompletionReference")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpCreateInCoreTaskResult), TypeInfoPropertyName = "McpMcpCreateInCoreTaskResult")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpCreateTaskResult), TypeInfoPropertyName = "McpMcpCreateTaskResult")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpCursorParams), TypeInfoPropertyName = "McpMcpCursorParams")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpDiscoverResult), TypeInfoPropertyName = "McpMcpDiscoverResult")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpEchoArguments), TypeInfoPropertyName = "McpMcpEchoArguments")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpEmbeddedResourceContent), TypeInfoPropertyName = "McpMcpEmbeddedResourceContent")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpEmptyResult), TypeInfoPropertyName = "McpMcpEmptyResult")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpGetPromptResult), TypeInfoPropertyName = "McpMcpGetPromptResult")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpIcon), TypeInfoPropertyName = "McpMcpIcon")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpImageContent), TypeInfoPropertyName = "McpMcpImageContent")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpImplementation), TypeInfoPropertyName = "McpMcpImplementation")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpInCoreTask), TypeInfoPropertyName = "McpMcpInCoreTask")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpInitializeParams), TypeInfoPropertyName = "McpMcpInitializeParams")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpInputRequest), TypeInfoPropertyName = "McpMcpInputRequest")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpInputRequiredResult), TypeInfoPropertyName = "McpMcpInputRequiredResult")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpJsonSchema), TypeInfoPropertyName = "McpMcpJsonSchema")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpLevelParams), TypeInfoPropertyName = "McpMcpLevelParams")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpListChangedCapability), TypeInfoPropertyName = "McpMcpListChangedCapability")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpListPromptsResult), TypeInfoPropertyName = "McpMcpListPromptsResult")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpListResourcesResult), TypeInfoPropertyName = "McpMcpListResourcesResult")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpListResourceTemplatesResult), TypeInfoPropertyName = "McpMcpListResourceTemplatesResult")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpListTasksResult), TypeInfoPropertyName = "McpMcpListTasksResult")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpListToolsResult), TypeInfoPropertyName = "McpMcpListToolsResult")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpLogMessageNotification), TypeInfoPropertyName = "McpMcpLogMessageNotification")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpNamedArgumentsParams), TypeInfoPropertyName = "McpMcpNamedArgumentsParams")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpPaginatedResult), TypeInfoPropertyName = "McpMcpPaginatedResult")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpProgressNotification), TypeInfoPropertyName = "McpMcpProgressNotification")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpPrompt), TypeInfoPropertyName = "McpMcpPrompt")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpPromptArgument), TypeInfoPropertyName = "McpMcpPromptArgument")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpPromptMessage), TypeInfoPropertyName = "McpMcpPromptMessage")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpProtectedResourceMetadata), TypeInfoPropertyName = "McpMcpProtectedResourceMetadata")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpReadResourceResult), TypeInfoPropertyName = "McpMcpReadResourceResult")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpResource), TypeInfoPropertyName = "McpMcpResource")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpResourceCapability), TypeInfoPropertyName = "McpMcpResourceCapability")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpResourceLinkContent), TypeInfoPropertyName = "McpMcpResourceLinkContent")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpResourceTemplate), TypeInfoPropertyName = "McpMcpResourceTemplate")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpResult), TypeInfoPropertyName = "McpMcpResult")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpServerCapabilities), TypeInfoPropertyName = "McpMcpServerCapabilities")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpSetLogLevelRequest), TypeInfoPropertyName = "McpMcpSetLogLevelRequest")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpSubscriptionFilter), TypeInfoPropertyName = "McpMcpSubscriptionFilter")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpTask), TypeInfoPropertyName = "McpMcpTask")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpTaskAck), TypeInfoPropertyName = "McpMcpTaskAck")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpTaskAugmentation), TypeInfoPropertyName = "McpMcpTaskAugmentation")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpTextContent), TypeInfoPropertyName = "McpMcpTextContent")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpTextResourceContents), TypeInfoPropertyName = "McpMcpTextResourceContents")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpToolCallResult), TypeInfoPropertyName = "McpMcpToolCallResult")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpUpdateTaskParams), TypeInfoPropertyName = "McpMcpUpdateTaskParams")]
    [JsonSerializable(typeof(Voltaic.Mcp.McpUriParams), TypeInfoPropertyName = "McpMcpUriParams")]
    [JsonSerializable(typeof(Voltaic.Mcp.ToolDefinition), TypeInfoPropertyName = "McpToolDefinition")]
    internal partial class VoltaicJsonContext : JsonSerializerContext
    {
    }
}
